name: Deploy Express JS Student API to EC2 Nginx Instance
on:
    push:
        branches:
          - express-js-api-basic # or your main branch
    workflow_dispatch:

jobs:
      deploy:
        environment: AWS-MYSQL-INSTANCE-FREE-TIER-ENV # explicitly declare environment to use the secret keys inside it
        runs-on: ubuntu-latest # or a self-hosted runner if preferred

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x' # or your desired Node.js version

        - name: Create build artifact 
          run: |
            cd ${{ github.workspace }}
            # Create a temporary directory in the runner's workspace
            mkdir temp_artifact
    
            rsync -a --exclude 'temp_artifact' . temp_artifact/
    

            # Run the tar command on the stable copy of your files
            tar -czf release.tar.gz -C temp_artifact .

        - name: Copy artifact to EC2 Debian Temp Directory
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.AWS_EC2_HOST_FREE_TIER }}
            username: ${{ secrets.AWS_EC2_INSTANCE_USERNAME_FREE_TIER }}
            key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY_FREE_TIER }}
            source: "release.tar.gz"
            target: "/tmp"

        

        - name: Deploy to Nginx Instance via SSH 
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.AWS_EC2_HOST_FREE_TIER }}
            username: ${{ secrets.AWS_EC2_INSTANCE_USERNAME_FREE_TIER }} # or your EC2 instance username
            key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY_FREE_TIER }}
            script: |
              cd /var/www/express-js-student-api
              # Optional: Clear old files to ensure a clean deployment
              rm -rf *

              sudo chown -R $USER:$USER .
              # Extract the artifact from /tmp
              tar -xzf /tmp/release.tar.gz
            
              # Delete the temporary artifact
              rm /tmp/release.tar.gz

              # Install dependencies and start or restart the app with PM2
              npm install
              pm2 startOrReload index.js --name express-js-student-api