
name: Automated API Testing via Postman Newman
on:
    push:
      branches:
        - express-js-api-basic
    workflow_dispatch:
    
jobs:
   start_testing:
      runs-on: ubuntu-latest

      env:
          # This maps your GitHub Secret to an environment variable the job can use
          POSTMAN_USERNAME: ${{ secrets.POSTMAN_USERNAME }}
          POSTMAN_PASSWORD: ${{ secrets.POSTMAN_PASSWORD }}

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Diagnostic Check Print Environment Variables
        run: |
          echo "Checking POSTMAN_USERNAME: $POSTMAN_USERNAME"
          echo "Checking POSTMAN_PASSWORD: $POSTMAN_PASSWORD"
      #- name: Install API Dependencies
        # This uses the package.json in the project root to install modules (like express)
       # run: npm install

      #- name: Start Express.js API Server
        # Use 'npm start' or the command that runs your API on port 3000
        # The '&' is crucial: it runs the command in the background
      #  run: PORT=3000 node express-js-api-basic/index.js &  

      #- name: Wait for API to be fully ready
        # Give the Express.js server 5-10 seconds to start listening on port 3000
      #  run: sleep 10 

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection with Newman
        
        run: |
          newman run express-js-api-basic/postman_test_collection/express-js-project-student-localhost.postman_collection.json \
          -e express-js-api-basic/postman_test_collection/Localhost.postman_environment.json \
          --env-var "username=$POSTMAN_USERNAME" \
          --env-var "password=$POSTMAN_PASSWORD"

